SET SQL_SAFE_UPDATES = 0;
DROP schema IF EXISTS university_sample;
create schema if not exists university_sample;
USE university_sample;
CREATE TABLE DEPARTMENT(
DEPARTMENTID INT PRIMARY KEY AUTO_INCREMENT,
DEPARTMENTNAME VARCHAR(255) NOT NULL,
ANNUALBUDGET INT NOT NULL,
NUMBEROFSTUDENTS INT NOT NULL
);

CREATE TABLE PROFESSOR(
PROFESSORID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
LASTNAME VARCHAR(255) NOT NULL,
GENDER VARCHAR(10) NOT NULL,
NUMBEROFPUBLICATIONS INT NOT NULL,
DEPTID INT NOT NULL,
FOREIGN KEY (DEPTID) 
    REFERENCES DEPARTMENT(DEPARTMENTID) 
    ON UPDATE RESTRICT 
    ON DELETE CASCADE
);

CREATE TABLE CLASSROOM(
CLASSROOMID INT PRIMARY KEY AUTO_INCREMENT,
CLASSNAME VARCHAR(255) NOT NULL,
BUILDING VARCHAR(2) NOT NULL,
CAPACITY INT NOT NULL,
CLASSTYPE VARCHAR(12) NOT NULL,
DEPTID INT NOT NULL,
FOREIGN KEY (DEPTID) 
    REFERENCES DEPARTMENT(DEPARTMENTID) 
    ON UPDATE RESTRICT 
    ON DELETE CASCADE
);