INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy A20','Samsung','Smartphone',158);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Pixel A3','Google','Smartphone',399);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy A10','Samsung','Smartphone',128);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone 7','Apple','Smartphone',210);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone 6','Apple','Smartphone',99);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Honor 8X','Huawei','Smartphone',174);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy A50','Samsung','Smartphone',250);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Redmi Note 7','Xiaomi','Smartphone',180);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Moto G7','Motorola','Smartphone',279);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Moto G6','Motorola','Smartphone',139);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy S9','Samsung','Smartphone',420);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone 6S','Apple','Smartphone',169);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy S8','Samsung','Smartphone',380);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone XS','Apple','Smartphone',900);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone X','Apple','Smartphone',720);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy Note 8','Samsung','Smartphone',309);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy Note 10','Samsung','Smartphone',1000);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Pixel XL','Google','Smartphone',220);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Surface Pro 6','Microsoft','Tablet',750);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Tab 4 10.1','Lenovo','Tablet',180);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy Tab A8','Samsung','Tablet',196);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Surface Go','Microsoft','Tablet',580);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Yoga Tab 3 Pro','Lenovo','Tablet',300);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('MediaPad','Huawei','Tablet',349);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPad Pro','Apple','Tablet',799);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPad','Apple','Tablet',329);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Chromebook','Lenovo','Computer',219);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Predator Helios 300','Acer','Computer',1099);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Aspire','Lenovo','Computer',314);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Chromebook','Asus','Computer',215);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Zenbook','Asus','Computer',999);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Pavilion','HP','Computer',340);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Vivobook','Asus','Computer',380);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('GL63','MSI','Computer',799);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Gear 3','Samsung','Smartwatch',277);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Apple Watch S3','Apple','Smartwatch',200);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Vivoactive','Garmin','Smartwatch',179);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Versa lite','Fitbit','Smartwatch',156);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Apple Watch S3','Apple','Smartwatch',200);